### ISSUE TITLE
Latest version is not on PSGallery

### ISSUE THREAD

**Issue by glvangorp** [rajivharris/Set-PsEnv#3]
Can you please upload the updated codebase to PSGallery. I'm using the package and need the updated string split pull request: https://github.com/rajivharris/Set-PsEnv/pull/1.

You can see that it is not there now: https://www.powershellgallery.com/packages/Set-PsEnv/0.0.2

**Comment by rajivharris** [comment]
Sure , will try to push the latest version over the weekend

**Comment by rajivharris** [comment]
@glvangorp 
Published new package. Please check and let me know
